// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

/// @title IGroth16Verifier
/// @notice Minimal interface for a Groth16 zk-SNARK verifier.
///         The actual verifier is generated by snarkjs/circom and deployed separately.
///         This interface decouples ZKStreakVerifier from any specific circuit version,
///         allowing the verifier contract to be upgraded without redeploying the registry.
interface IGroth16Verifier {
    /// @notice Verify a Groth16 proof
    /// @param pA         Proof element A (G1 point)
    /// @param pB         Proof element B (G2 point)
    /// @param pC         Proof element C (G1 point)
    /// @param pubSignals Public inputs: [nullifier, streakCommitment, minStreak]
    /// @return True if the proof is valid
    function verifyProof(
        uint256[2]    calldata pA,
        uint256[2][2] calldata pB,
        uint256[2]    calldata pC,
        uint256[]     calldata pubSignals
    ) external view returns (bool);
}
