const { ethers } = require("hardhat");
const fs   = require("fs");
const path = require("path");

async function deployWithRetry(factory, args = [], retries = 5) {
  for (let i = 0; i < retries; i++) {
    try {
      const contract = await ethers.deployContract(factory, args);
      await contract.waitForDeployment();
      return contract;
    } catch (e) {
      if (i === retries - 1) throw e;
      console.log(`  ↻ retry ${i + 1}/${retries - 1}...`);
      await new Promise(r => setTimeout(r, 4000));
    }
  }
}

const ZK_STREAK_VERIFIER = "0xC3333e5f5c29B624B40fc8E7D3F70Ec71CED558B";

async function main() {
  const [deployer] = await ethers.getSigners();
  const network    = await ethers.provider.getNetwork();
  console.log("Deployer:", deployer.address);
  console.log("Network :", network.name);

  // 1. Deploy the real Groth16 verifier generated by snarkjs
  const verifier = await deployWithRetry("Groth16Verifier");
  const verifierAddr = await verifier.getAddress();
  console.log("Groth16Verifier    :", verifierAddr);

  // 2. Point the live ZKStreakVerifier at the real verifier
  const zkAbi = ["function setVerifier(address) external"];
  const zk = new ethers.Contract(ZK_STREAK_VERIFIER, zkAbi, deployer);
  await (await zk.setVerifier(verifierAddr)).wait();
  console.log("ZKStreakVerifier.setVerifier ✓");

  // 3. Patch deployments file
  const outPath = path.join(__dirname, `../deployments.${network.name}.json`);
  const deployments = JSON.parse(fs.readFileSync(outPath, "utf8"));
  deployments.Groth16Verifier = verifierAddr;
  deployments.deployedAt      = new Date().toISOString();
  fs.writeFileSync(outPath, JSON.stringify(deployments, null, 2));
  console.log("deployments.celo.json updated ✓");
}

main().catch((e) => { console.error(e); process.exit(1); });
