// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import "@openzeppelin/contracts/access/Ownable.sol";
import "./interfaces/IGroth16Verifier.sol";

/// @title ZKStreakVerifier
/// @notice Verifies zero-knowledge proofs of habit streaks without revealing the raw streak data.
///
/// @dev    Circuit design (off-chain, circom):
///           Private inputs: streakDays, salt
///           Public  inputs: nullifier = hash(userAddress, salt)
///                           streakCommitment = hash(streakDays, salt)
///                           minStreak (threshold being proven, e.g. 7 / 30 / 100)
///
///         The circuit proves: streakDays >= minStreak
///         without revealing the actual streakDays value.
///
///         Nullifiers prevent the same proof from being replayed.
///         The verifier contract (IGroth16Verifier) is generated by snarkjs
///         and can be upgraded by the owner without redeploying this registry.
contract ZKStreakVerifier is Ownable {
    /// @notice The deployed Groth16 verifier contract
    IGroth16Verifier public verifier;

    /// @dev nullifier => used — prevents proof replay attacks
    mapping(bytes32 => bool) public nullifierUsed;

    /// @dev user => milestone threshold => proven
    mapping(address => mapping(uint256 => bool)) public milestoneProven;

    event StreakProven(
        address indexed user,
        uint256 indexed minStreak,
        bytes32 indexed nullifier
    );
    event VerifierUpdated(address indexed oldVerifier, address indexed newVerifier);

    constructor(address _verifier) Ownable(msg.sender) {
        require(_verifier != address(0), "Zero verifier");
        verifier = IGroth16Verifier(_verifier);
    }

    /// @notice Submit a ZK proof that streakDays >= minStreak
    /// @param pA         Groth16 proof element A
    /// @param pB         Groth16 proof element B
    /// @param pC         Groth16 proof element C
    /// @param pubSignals [nullifier, streakCommitment, minStreak]
    function proveStreak(
        uint256[2]    calldata pA,
        uint256[2][2] calldata pB,
        uint256[2]    calldata pC,
        uint256[]     calldata pubSignals
    ) external {
        require(pubSignals.length == 3, "Invalid signals");

        bytes32 nullifier = bytes32(pubSignals[0]);
        uint256 minStreak = pubSignals[2];

        require(!nullifierUsed[nullifier], "Proof already used");
        require(verifier.verifyProof(pA, pB, pC, pubSignals), "Invalid proof");

        nullifierUsed[nullifier] = true;
        milestoneProven[msg.sender][minStreak] = true;

        emit StreakProven(msg.sender, minStreak, nullifier);
    }

    /// @notice Returns true if a user has proven a streak >= minStreak
    function hasProvenStreak(address user, uint256 minStreak) external view returns (bool) {
        return milestoneProven[user][minStreak];
    }

    /// @notice Upgrade the verifier contract (e.g. after circuit update)
    function setVerifier(address _verifier) external onlyOwner {
        require(_verifier != address(0), "Zero verifier");
        emit VerifierUpdated(address(verifier), _verifier);
        verifier = IGroth16Verifier(_verifier);
    }
}
